theme: jekyll-theme-hacker

# Site settings
title: Amiga 500 Undead
description: A "brain transplant" for the Amiga 500, replacing its motherboard with a modern single-board computer while preserving the original keyboard, joystick ports, and LED drive indicators.
