name: Build Arduino Leonardo Kyb

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive  # This initializes and updates submodules recursively

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install Arduino core
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr

    - name: Install Keyboard library
      run: |
        arduino-cli lib install "Keyboard"

    - name: Compile Sketch
      run: |
        arduino-cli compile --fqbn arduino:avr:leonardo Amiga500-USB-Keyboard-Leonardo/Amiga500-USB-Keyboard-Leonardo.ino
