name: Build LED Control

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile C program
      run: |
        gcc -o led_control/amiga_led_control_odroid led_control/amiga_led_control_odroid.c
