name: Build LED Control

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf libc6-dev

    - name: Compile C program
      run: |
        arm-linux-gnueabihf-gcc -o led_control/amiga_led_control_odroid led_control/amiga_led_control_odroid.c
